package com.p.SpringProject;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/customer-api", method = {RequestMethod.GET, RequestMethod.POST}) // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called customerRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CustomerRepository customerRepository;

    //  Creates a new Customer
    //  Returns new users generated id
    @GetMapping(path = "/create")
    public @ResponseBody
    Customer addNewUser(@RequestParam String name, @RequestParam String address
            , @RequestParam String phone) throws Exception {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Customer n = new Customer();
        n.setName(name);
        n.setAddress(address);
        n.setPhone(phone);
        n.setId();

        customerRepository.save(n);
        return n;
    }


    //  Returns all users
    @GetMapping(path = "/read-all")
    public @ResponseBody
    Iterable<Customer> getAllUsers() {
        // This returns a JSON or XML with the users
        return customerRepository.findAll();
    }

    //  Deletes all users
    @DeleteMapping(path = "/delete-all")
    @Transactional
    public @ResponseBody
    String deleteUser() {

        customerRepository.deleteAll();

        return "Done";
    }


    //  Return user by it's id
    @GetMapping(path = "/get/{id}")
    public @ResponseBody
    Customer getUser(@PathVariable Integer id) {

        Customer customer = customerRepository.findById(id);

        if(customer==null){
            throw new IllegalArgumentException();
        }

        return customerRepository.findById(id);
    }


    //  Select user by id and update one or more of it's fields
    @PostMapping("/update/{id}")
    @Transactional
    public @ResponseBody
    String editUser(@PathVariable Integer id/*@RequestParam Integer id*/, @RequestParam(required = false) String name,
                    @RequestParam(required = false) String address, @RequestParam(required = false) String phone) throws Exception {
        Customer n = new Customer();

        Customer customer = customerRepository.findById(id);
        if (name!=null) customer.setName(name);
        if (address!=null) customer.setAddress(address);
        if (phone!= null) customer.setPhone(phone);

        customerRepository.save(customer);

        return "Done";
    }


    //  Delete user by id
    @DeleteMapping(path = "/delete/{id}")
    @Transactional
    public @ResponseBody
    String deleteUser(@PathVariable Integer id) {

        Customer customer = customerRepository.findById(id);
        customerRepository.delete(customer);

        return "Done";
    }

}
